-- ISPMan: "Other" (non-service) payments, payment categories, and paid_on.
--
-- RUN THIS IN THE SUPABASE SQL EDITOR.
--
-- NOT YET APPLIED. Until it is, the payment type toggle and the receipt's
-- "Other" mode hide themselves and the Service flow is untouched
-- (see lib/schema.ts#otherPayments).
--
-- ===========================================================================
-- THREE DEVIATIONS FROM THE SUPPLIED SQL. READ BEFORE RUNNING.
-- ===========================================================================
--
-- (1) payment_type -> payment_kind
--
-- The supplied SQL asked for:
--
--   ADD COLUMN IF NOT EXISTS payment_type TEXT NOT NULL DEFAULT 'service'
--     CHECK (payment_type IN ('service','other'))
--
-- `payments.payment_type` ALREADY EXISTS: VARCHAR(50) DEFAULT 'cash', holding
-- the *payment method* (cash/card/online). It is the older, narrower column
-- that 0010 superseded with `payment_method` but deliberately kept writing so
-- historical reads keep working. All 62 live rows have it populated.
--
-- Run as supplied, ADD COLUMN IF NOT EXISTS would be a SILENT NO-OP: no error,
-- no column, and no CHECK constraint. The migration reports success having
-- changed nothing, and application code then writing 'service'/'other' would
-- overwrite the method on every new row with nothing to stop it. It would also
-- break the historical fallback `payment_method ?? payment_type` in
-- lib/data/checkoff.ts and lib/data/payments.ts, and the `.eq('payment_type')`
-- method filter at lib/data/payments.ts:85.
--
-- The service/other flag is therefore a new column, `payment_kind`.
-- payment_type keeps its current meaning and is not touched.
--
-- (2) misc_categories -> new payment_categories table
--
-- The supplied SQL pointed misc_category_id at misc_categories. That table is
-- the customer *segment* list (School, Government, Hotel, Church), assigned via
-- customers.misc_category_id in the customer form and Settings > Misc
-- Categories. Adding "Installation" there would make it selectable as a
-- customer segment, which the brief's "do not change existing uses of
-- misc_categories elsewhere" rules out.
--
-- Payment purposes get their own per-company table instead. misc_categories is
-- left exactly as it is.
--
-- (3) paid_on backfilled from payment_date, not created_at
--
-- `payment_date` (TIMESTAMPTZ DEFAULT now()) is already the *business* date and
-- is already accepted from the form (app/actions/payments.ts:91, 629);
-- `created_at` is the row insert time. Every existing report already filters
-- and orders on payment_date. Backfilling from created_at would silently
-- restate the date of any back-dated payment.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- Payment categories (the "Purpose" list)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.payment_categories (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id  BIGINT      NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  name        VARCHAR(60) NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 60 chars matches the limit the brief sets on the inline "add new category"
-- input, so a name typed at the till cannot be rejected by the column.

-- Purposes are per company, and a company cannot hold the same one twice.
-- Case-insensitive so "Installation" and "installation" collide, which is what
-- someone adding a category inline at the till expects.
CREATE UNIQUE INDEX IF NOT EXISTS payment_categories_company_name_idx
  ON public.payment_categories (company_id, lower(name));

ALTER TABLE public.payment_categories ENABLE ROW LEVEL SECURITY;

-- Matches the shape used by every other tenant table (0001) and the catalogue
-- policies as corrected by 0006: scoped to `authenticated`, never PUBLIC.
DROP POLICY IF EXISTS payment_categories_company ON public.payment_categories;
CREATE POLICY payment_categories_company ON public.payment_categories
  FOR ALL TO authenticated
  USING (company_id = public.current_company_id())
  WITH CHECK (company_id = public.current_company_id());


-- ---------------------------------------------------------------------------
-- payments: kind, purpose, and business date
-- ---------------------------------------------------------------------------
ALTER TABLE public.payments
  -- 'service' = the existing billing flow. 'other' = a one-off charge
  -- (installation, router sale, ...) that touches no billing field, no
  -- carried balance, and no RADIUS state.
  ADD COLUMN IF NOT EXISTS payment_kind TEXT DEFAULT 'service',
  -- The purpose of an 'other' payment. NULL on every service payment.
  ADD COLUMN IF NOT EXISTS payment_category_id BIGINT
    REFERENCES public.payment_categories(id),
  -- The business date of the payment, editable at the till.
  ADD COLUMN IF NOT EXISTS paid_on DATE,
  -- ADDITION BEYOND THE SUPPLIED SQL, and the receipt cannot be correct
  -- without it. The service receipt prints:
  --
  --     Monthly service         3,500.00
  --     Balance b/f             1,200.00
  --     Total due               4,700.00
  --
  -- "Balance b/f" is carried_balance_before and "Balance" is
  -- carried_balance_after (both from 0011), but the monthly charge itself is
  -- nowhere on the payments row. It is customers.monthly_rate plus every
  -- active add-on, computed at the till (app/actions/payments.ts:180).
  --
  -- It cannot be derived back out afterwards: carried_after saturates at 0, so
  -- a payment that cleared the bill loses the figure entirely. And it must not
  -- be recomputed at reprint time -- the rate or the add-ons may have changed
  -- since, which would make a reprint differ from the original. The brief
  -- requires a reprint to be identical, so the figure is stamped on the row.
  ADD COLUMN IF NOT EXISTS service_charge NUMERIC,
  -- ADDITION BEYOND THE SUPPLIED SQL. The expiry actually written to radcheck
  -- by this payment, for the "Service active until" line.
  --
  -- Distinct from access_granted_until (0011), which is stamped with the expiry
  -- the payment was INTENDED to buy and is written even when the RADIUS write
  -- is skipped, fails, or the customer was never provisioned. The receipt must
  -- show what the registry actually holds and must omit the line when no expiry
  -- was set, so it needs the applied value, left NULL when access did not move.
  ADD COLUMN IF NOT EXISTS service_active_until DATE;

-- A DEFAULT does not apply to rows that already exist, so backfill before the
-- NOT NULL or the ALTER fails on all 62 historical rows.
UPDATE public.payments SET payment_kind = 'service' WHERE payment_kind IS NULL;
ALTER TABLE public.payments ALTER COLUMN payment_kind SET NOT NULL;

ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_payment_kind_check;
ALTER TABLE public.payments ADD CONSTRAINT payments_payment_kind_check
  CHECK (payment_kind IN ('service','other'));

-- See deviation (3). payment_date is the business date; created_at is not.
UPDATE public.payments SET paid_on = payment_date::date WHERE paid_on IS NULL;
-- Rows with no payment_date at all (there should be none) fall back to insert date.
UPDATE public.payments SET paid_on = created_at::date   WHERE paid_on IS NULL;

-- An 'other' payment must name its purpose; a service payment must not carry one.
-- Deferred to the end so the backfill above is not fighting it.
ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_category_kind_check;
ALTER TABLE public.payments ADD CONSTRAINT payments_category_kind_check
  CHECK (
    (payment_kind = 'other'   AND payment_category_id IS NOT NULL) OR
    (payment_kind = 'service' AND payment_category_id IS NULL)
  );

-- NOTE: no CHECK for "paid_on is not in the future". CURRENT_DATE is not
-- IMMUTABLE, so Postgres rejects it in a CHECK constraint. The future-date rule
-- is enforced in app/actions/payments.ts and by the date input's max attribute.

-- Reporting reads collections by day; the payments list filters by kind.
CREATE INDEX IF NOT EXISTS payments_paid_on_idx
  ON public.payments (company_id, paid_on DESC);
CREATE INDEX IF NOT EXISTS payments_payment_kind_idx
  ON public.payments (company_id, payment_kind);


-- ---------------------------------------------------------------------------
-- Verify afterwards. Expected results in comments.
-- ---------------------------------------------------------------------------
--   SELECT payment_kind, count(*) FROM payments GROUP BY 1;
--     -> service | 62
--
--   SELECT count(*) FROM payments WHERE paid_on IS NULL;
--     -> 0
--
--   SELECT count(*) FROM payments WHERE paid_on <> payment_date::date;
--     -> 0
--
--   SELECT id, payment_type, payment_method FROM payments ORDER BY id DESC LIMIT 3;
--     -> payment_type still cash/card/online, unchanged
--
--   SELECT count(*) FROM payments WHERE service_charge IS NULL;
--     -> 62 (every historical row; see below)
--
-- service_charge and service_active_until are deliberately NOT backfilled. The
-- monthly charge in force when a historical payment was taken is not
-- recoverable, and inventing one from today rate would print a wrong figure on
-- a reprinted receipt. Receipts for pre-0013 payments therefore omit the
-- "Monthly service"/"Total due" breakdown and print the amount paid only.
-- See lib/receipt.ts#buildReceipt.
