-- ISPMan: per-bill history.
--
-- RUN THIS IN THE SUPABASE SQL EDITOR.
--
-- ===========================================================================
-- NOT YET APPLIED, AND NOT YET WRITTEN TO. THIS FILE IS FOR REVIEW.
-- ===========================================================================
--
-- Nothing in the application reads or writes `bills` yet. Bill All
-- (app/actions/bulk.ts#billBatch) has deliberately NOT been changed: applying
-- this migration on its own is inert and safe, and the app behaves exactly as
-- it does today. The build that fills the table is a separate piece of work —
-- see "WHAT HAS TO CHANGE IN THE APP" at the foot of this file.
--
-- ---------------------------------------------------------------------------
-- WHY
-- ---------------------------------------------------------------------------
-- Bill All currently records a run in two places, neither of which is history:
--
--   customers.carried_balance   a running total. Says what is owed in
--                               aggregate, never what any one bill was for.
--   customers.last_billed_date  OVERWRITTEN every run. A customer billed for
--                               July and then August retains only 2026-08-31;
--                               July is unrecoverable.
--
-- The only other trace is one free-text `bulk_bill` row in `log` per run.
--
-- Two things follow from that, both of which this table fixes:
--
--   1. The dashboard cannot attribute billing to the period it covers. The
--      "Revenue Over Time" chart's first series was labelled "Total Billed"
--      but was never billing at all — it is the sum of every onboarded
--      customer's CURRENT monthly_rate, cumulative and retroactively restated
--      whenever a rate changes. It has since been renamed "Recurring Monthly
--      Value" (lib/data/dashboard.ts#RevenuePoint) because no honest billing
--      series can be computed from the present schema.
--
--   2. Double-billing is prevented only by an application WHERE clause.
--      billBatch() re-asserts "not already billed for this period" on every
--      UPDATE, which is correct and handles two operators racing — but it is a
--      guarantee that lives in TypeScript. The UNIQUE constraint below moves it
--      into Postgres, where a bug, a script or a psql session cannot get around
--      it. Given that a duplicate run silently doubles every balance in the
--      company with no way to detect it afterwards, that is the single most
--      valuable line in this file.

-- ---------------------------------------------------------------------------
-- 1. The table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bills (
  id BIGSERIAL PRIMARY KEY,

  -- Tenant scoping, matching every other table here. Denormalised onto the row
  -- rather than reached through customers, because the RLS policy below and
  -- every dashboard query filter on it directly.
  company_id BIGINT NOT NULL REFERENCES companies(id),

  customer_id BIGINT NOT NULL REFERENCES customers(id),

  -- THE PERIOD BILLED FOR, never the date the run happened. Billing August 2026
  -- stores 2026-08-01 .. 2026-08-31 whether the run is on 1 September or on
  -- 14 October. This is the same rule billBatch() already applies to
  -- last_billed_date, promoted to a first-class pair of columns.
  --
  -- Stored as a start/end pair rather than a 'YYYY-MM' text month so a future
  -- non-calendar cycle (mid-month to mid-month, a pro-rated first period) needs
  -- no migration, and so range queries are plain date comparisons.
  period_start DATE NOT NULL,
  period_end   DATE NOT NULL,

  -- What was added to carried_balance. The customer's monthly_rate AS IT WAS AT
  -- RUN TIME — this is why the table is needed: reading monthly_rate back today
  -- gives the current rate, not the one billed.
  amount NUMERIC(10,2) NOT NULL,

  -- The balance either side of this bill. Follows the pattern payments already
  -- uses (carried_balance_before / carried_balance_after, migration 0011) and
  -- is what makes a run reconstructible — and reversible — after the fact.
  carried_balance_before NUMERIC(10,2),
  carried_balance_after  NUMERIC(10,2),

  -- When the run actually happened, and who clicked it. Deliberately separate
  -- from the period: "billed late" is a real thing an operator needs to see.
  run_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  run_by BIGINT REFERENCES users(id),

  -- Groups every row written by ONE press of Bill All. Without it there is no
  -- way to ask "what did that run touch?" or to reverse one run without
  -- catching a later correction in the same net. Generated by the app, not a
  -- DEFAULT, so all rows in a run share one value.
  run_id UUID NOT NULL
);

-- ---------------------------------------------------------------------------
-- 2. The constraint that actually prevents double billing
-- ---------------------------------------------------------------------------
-- One bill per customer per period, enforced by Postgres.
--
-- With this in place a second Bill All for the same month cannot write a second
-- charge even if every application guard were removed: the insert fails. The
-- app would treat a conflict on this constraint as "already billed", which is
-- the same outcome billBatch() reports today — but earned from the database
-- rather than asserted by the caller.
--
-- Keyed on period_start alone rather than the (start, end) pair: two runs
-- disagreeing about the end of August must still collide, not sit side by side.
CREATE UNIQUE INDEX IF NOT EXISTS bills_customer_period_key
  ON bills (customer_id, period_start);

-- Sanity checks. Cheap, and they catch a caller that has its arguments crossed.
ALTER TABLE bills DROP CONSTRAINT IF EXISTS bills_period_order_check;
ALTER TABLE bills ADD CONSTRAINT bills_period_order_check
  CHECK (period_end >= period_start);

ALTER TABLE bills DROP CONSTRAINT IF EXISTS bills_amount_check;
ALTER TABLE bills ADD CONSTRAINT bills_amount_check
  CHECK (amount >= 0);

-- ---------------------------------------------------------------------------
-- 3. Indexes
-- ---------------------------------------------------------------------------
-- The dashboard chart: sum(amount) grouped by period, for one company, over the
-- last six months. Without this it is a full scan per page load.
CREATE INDEX IF NOT EXISTS bills_company_period_idx
  ON bills (company_id, period_start);

-- "Show me that run" / "reverse that run".
CREATE INDEX IF NOT EXISTS bills_run_idx
  ON bills (company_id, run_id);

-- A customer's own billing history on their detail page.
-- (customer_id alone is already the leading column of bills_customer_period_key,
--  so no separate index is needed for it.)

-- ---------------------------------------------------------------------------
-- 4. RLS
-- ---------------------------------------------------------------------------
-- Same shape as checkoff_records in 0010.
ALTER TABLE bills ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bills_company ON bills;
CREATE POLICY bills_company
  ON bills FOR ALL TO authenticated
  USING (company_id = current_company_id())
  WITH CHECK (company_id = current_company_id());

-- ---------------------------------------------------------------------------
-- 5. No backfill
-- ---------------------------------------------------------------------------
-- Deliberately none, and it cannot be faked.
--
-- The only surviving evidence of past runs is customers.last_billed_date (the
-- LATEST period per customer) and the free-text `bulk_bill` log rows. A
-- backfill from either would invent per-customer amounts that were never
-- recorded — reading today's monthly_rate as though it were the rate billed
-- three months ago — and those invented rows would be indistinguishable from
-- real ones afterwards.
--
-- The chart therefore starts empty and fills from the first run after this
-- lands. An empty series is a true statement; a fabricated one is not.

-- Verify afterwards:
--
--   SELECT * FROM bills LIMIT 1;                        -- table exists, empty
--   \d bills                                            -- constraints + indexes

-- ===========================================================================
-- WHAT HAS TO CHANGE IN THE APP (NOT DONE — FOR THE NEXT PIECE OF WORK)
-- ===========================================================================
--
-- (a) lib/schema.ts — add a `bills` capability probe, so the app runs
--     unchanged until this migration is applied. Every other table added since
--     0003 follows this pattern; without it the first query rejects.
--
-- (b) app/actions/bulk.ts#billBatch — insert one row per customer billed,
--     inside the same step that updates carried_balance, sharing one run_id
--     generated by the caller. Open question below.
--
-- (c) app/actions/customers.ts#deleteCustomer — MUST be updated in the same
--     change. It clears dependents by hand (log, notifications_queue,
--     support_tickets, payments) before deleting the customer. `bills` has a
--     NOT NULL FK to customers, so without adding it to that list every
--     customer deletion starts failing with a foreign key violation. See the
--     retention question below before deciding HOW it is handled.
--
-- (d) lib/data/dashboard.ts — a real billed series: sum(amount) grouped by
--     period_start. The existing `recurring` series stays as it is; this is a
--     third line, not a replacement.
--
-- ===========================================================================
-- THREE THINGS TO DECIDE BEFORE THIS IS BUILT
-- ===========================================================================
--
-- (1) ATOMICITY. Writing a bill row and updating carried_balance are two
--     statements over PostgREST, which has no client-side transaction. A crash
--     between them leaves a charge with no record, or a record with no charge.
--     Options: a SECURITY DEFINER function doing both in one statement (adds a
--     second hand-run migration, makes billBatch a single RPC call), or accept
--     the window and reconcile from bills. The unique constraint makes the
--     second failure mode self-correcting on a re-run; the first is not.
--     RECOMMENDATION: the function. It also makes the guard atomic.
--
-- (2) RETENTION ON CUSTOMER DELETE. Financial history normally outlives the
--     customer record, but the FK above is NOT NULL and deleteCustomer expects
--     to clear dependents. Three ways:
--       - delete the bills too (simplest, matches how payments are treated
--         today, loses the money trail);
--       - ON DELETE SET NULL with a nullable customer_id plus a denormalised
--         customer_name (keeps totals correct, keeps the name readable);
--       - block deletion of a customer who has been billed.
--     This file assumes NOTHING and leaves the FK strict, because the choice
--     changes the column definition. It has to be settled before the table is
--     written to — changing it afterwards means migrating real rows.
--
-- (3) WHETHER last_billed_date STAYS. Once bills exists it is derivable
--     (MAX(period_end) per customer) and the two can drift. Keeping it as a
--     cached value is fine; it should stop being the idempotency guard, since
--     the unique index does that job properly. Not urgent, and not a reason to
--     hold up (a)-(d).
