-- ISPMan: per-company switches for the two first-period rules.
--
-- RUN THIS IN THE SUPABASE SQL EDITOR.
--
-- NOT YET APPLIED. lib/schema.ts#firstPeriod probes for these two columns, and
-- until they exist the app behaves EXACTLY as it does today: the 21-day rule on
-- (it is unconditional in the current code), pro-rata off (it does not exist
-- yet). That asymmetry is deliberate — see the fallback note in lib/schema.ts.
--
-- READ THIS BEFORE APPLYING
-- Both columns default TRUE, so applying this migration TURNS PRO-RATA ON FOR
-- EVERY COMPANY AT ONCE. That is a change to what customers are charged for
-- their first payment, not a display change. If you would rather it be opt-in,
-- change the DEFAULT on prorata_first_payment_enabled to FALSE below BEFORE
-- running this — it is one word, and it is much easier than switching it back
-- off per company afterwards.
--
-- The 21-day rule's default of TRUE is different in kind: it preserves the
-- behaviour that is already live, so it changes nothing on apply.

-- ---------------------------------------------------------------------------
-- settings.first_expiry_rule_enabled — CHANGE A, the 21-day rule.
--
-- The rule itself already exists and is not being rebuilt: lib/expiry.ts
-- #firstExpiry, reached through lib/radius/operations.ts#provisionExpiry. A
-- customer's first expiry is the first cut-off day at least 21 days out, so
-- somebody switched on four days before their cut-off gets a short month plus
-- a full one rather than a stub they paid a full month for.
--
-- 21 IS FIXED IN CODE AND IS NOT A SETTING. It is the boundary between "a
-- period worth billing" and "a stub", not a company preference, and exposing it
-- would invite a tenant to set it to 3 and quietly recreate the problem the
-- rule exists to solve.
--
-- Switched OFF, a first provision walks to the plain next cut-off day, which is
-- what a reconnection does (lib/radius/operations.ts#reconnectExpiry).
--
-- PROVISIONING ONLY, either way. Renewals and reconnections never consult this.
-- ---------------------------------------------------------------------------
ALTER TABLE public.settings
  ADD COLUMN IF NOT EXISTS first_expiry_rule_enabled BOOLEAN NOT NULL DEFAULT TRUE;

-- ---------------------------------------------------------------------------
-- settings.prorata_first_payment_enabled — CHANGE B, pro-rata first payment.
--
-- daily = monthly_charge / 30
-- first payment = monthly_charge + (days beyond 30 x daily)
--
-- where `days` is the length of the first period: provisioning date to the
-- expiry that provisioning wrote. A customer connected on the 20th with a
-- cut-off of the 5th is buying 46 days and is charged for 46 days.
--
-- NEVER LESS THAN THE MONTHLY CHARGE. A first period SHORTER than 30 days is
-- charged the full rate; the difference is offered to the cashier as a discount
-- they may apply, and is never applied automatically. Any role may apply it,
-- and doing so writes a `first_period_discount` log row naming the agent — a
-- discretionary reduction in money owed is exactly the kind of decision that
-- has to be attributable afterwards.
--
-- 30 IS A DIVISOR, NOT A CALENDAR MONTH. The daily rate is the monthly charge
-- over 30 regardless of how long the actual month is, which is what makes the
-- arithmetic checkable at the counter with a phone calculator. Do not "fix"
-- this to use the real month length.
--
-- INDEPENDENT OF CHANGE A. Either may be on with the other off. With A off and
-- B on a first period can only ever be shorter than a month, so B degrades to
-- "full rate, discount offered" — which is coherent, and is why they are two
-- columns rather than one mode.
-- ---------------------------------------------------------------------------
ALTER TABLE public.settings
  ADD COLUMN IF NOT EXISTS prorata_first_payment_enabled BOOLEAN NOT NULL DEFAULT TRUE;

-- ---------------------------------------------------------------------------
-- NO SCHEMA IS ADDED FOR "HAS THIS CUSTOMER PAID SINCE PROVISIONING"
--
-- Deliberately no activated_at column. The provisioning moment is already
-- recorded: app/actions/customers.ts#provisionCustomer writes a
-- `network_provision` row into `log` with the customer id and a timestamp, and
-- lib/data/first-period.ts reads it back. Adding a column would make a second
-- copy of a fact the log already holds, and the two would drift the first time
-- one was written without the other.
--
-- The three conditions are in lib/data/first-period.ts. The one worth repeating
-- here is why the ~1,285 migrated West Central and Ezmze subscribers can never
-- be caught by this: scripts/migrate-legacy-company.mjs writes NO log rows at
-- all, and bulk provisioning writes ONE `bulk_provision` row with a null
-- customer id (app/actions/bulk.ts#logBulkProvision) rather than one
-- `network_provision` row per customer. Neither produces the anchor, so neither
-- can produce a first period.
--
-- The consequence, accepted knowingly: a genuinely new customer who is BULK
-- provisioned gets no pro-rata either. Bulk provision means "these already have
-- service" in this codebase — the same reasoning already stops it applying the
-- 21-day rule (app/actions/bulk.ts#expiryForCustomer).
-- ---------------------------------------------------------------------------
