-- ISPMan: one-off charges (installation, hardware, reconnection, ...).
--
-- RUN THIS IN THE SUPABASE SQL EDITOR.
--
-- ===========================================================================
-- NOT YET APPLIED. SAFE IN EITHER ORDER WITH THE CODE.
-- ===========================================================================
--
-- The code probes for this file (lib/schema.ts#charges) and hides every part
-- of the feature until it is present, so deploying first changes nothing and
-- applying first changes nothing either. Depends only on 0013 (payment_kind,
-- payment_categories), which is applied.
--
-- WHAT IT ADDS
--
--   1. customer_charges        one row per charge a manager puts on a customer
--   2. payments.charge_id      the charge a payment settles, NULL otherwise
--      payments.visit_id       ties the rows of one till visit together
--      payments.charge_outstanding_before
--                              what the charge still owed when this payment
--                              was taken, stamped so a reprint can restate it
--   3. payments_charge_guard   the trigger that keeps a charge from being paid
--                              past what it owes, or paid after it is voided
--
-- WHAT IT DELIBERATELY DOES NOT ADD
--
--   - A stored outstanding figure. Outstanding is amount less the payments
--     against it, derived on read. A payment edited or deleted afterwards
--     restates the charge with it, and there is no second balance to drift.
--   - Any link to carried_balance, account_credit, expiry or radcheck. A
--     one-off charge is money owed and nothing else. The service balance alone
--     decides access.
--   - A second category list. The category is payment_categories (0013), the
--     same Purpose list the till already uses for "other" payments.


-- ---------------------------------------------------------------------------
-- 1. customer_charges
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.customer_charges (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id  BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  -- CASCADE: deleting a customer already removes every payment they made
  -- (app/actions/customers.ts#deleteCustomer); a charge with no customer is
  -- not a debt anybody can be asked for.
  customer_id BIGINT NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  payment_category_id BIGINT NOT NULL REFERENCES public.payment_categories(id),
  amount      NUMERIC(10,2) NOT NULL,
  note        TEXT,
  -- The business date of the charge, as a manager states it. Not created_at.
  charged_on  DATE NOT NULL DEFAULT CURRENT_DATE,
  created_by  BIGINT,
  created_by_name TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- VOIDING WRITES OFF WHAT IS STILL OWED; THE PAID PART STANDS. There is no
  -- written_off column: what was written off is amount less what was paid,
  -- derived exactly as outstanding is, so it cannot disagree with the payments.
  voided_at   TIMESTAMPTZ,
  voided_by   BIGINT,
  voided_by_name TEXT,
  void_reason TEXT,

  CONSTRAINT customer_charges_amount_check CHECK (amount > 0),
  CONSTRAINT customer_charges_void_check CHECK (
    (voided_at IS NULL AND void_reason IS NULL) OR
    (voided_at IS NOT NULL AND void_reason IS NOT NULL AND length(trim(void_reason)) > 0)
  )
);

CREATE INDEX IF NOT EXISTS customer_charges_customer_idx
  ON public.customer_charges (company_id, customer_id);

ALTER TABLE public.customer_charges ENABLE ROW LEVEL SECURITY;

-- Same shape as payment_categories (0013) and every other tenant table.
DROP POLICY IF EXISTS customer_charges_company ON public.customer_charges;
CREATE POLICY customer_charges_company ON public.customer_charges
  FOR ALL TO authenticated
  USING (company_id = public.current_company_id())
  WITH CHECK (company_id = public.current_company_id());


-- ---------------------------------------------------------------------------
-- 2. payments: which charge, which visit, and what was owed
-- ---------------------------------------------------------------------------
ALTER TABLE public.payments
  -- SET NULL, not CASCADE: the money was received whatever happens to the
  -- charge, and a payment row must never disappear because a charge did.
  ADD COLUMN IF NOT EXISTS charge_id BIGINT
    REFERENCES public.customer_charges(id) ON DELETE SET NULL,
  -- One till visit, one receipt. Every row written by one submission of the
  -- payment form carries the same value; the receipt reads them together.
  -- NULL on every row written before this file and on single-row payments
  -- taken the old way.
  ADD COLUMN IF NOT EXISTS visit_id UUID,
  ADD COLUMN IF NOT EXISTS charge_outstanding_before NUMERIC(10,2);

-- A payment against a charge is an "other" payment. The category is checked
-- against the charge's by the trigger below, which can see both rows.
ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_charge_kind_check;
ALTER TABLE public.payments ADD CONSTRAINT payments_charge_kind_check
  CHECK (charge_id IS NULL OR payment_kind = 'other');

CREATE INDEX IF NOT EXISTS payments_charge_idx
  ON public.payments (charge_id) WHERE charge_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS payments_visit_idx
  ON public.payments (company_id, visit_id) WHERE visit_id IS NOT NULL;


-- ---------------------------------------------------------------------------
-- 3. The guard
--
-- ONE RULE, IN THE DATABASE, FOR EVERY WRITER. The till, a payment edit, a
-- script and a psql session all go through it. Two cashiers paying the same
-- charge at once serialise on the charge row's lock, and the second sees the
-- first's payment when it sums.
--
-- Refuses:
--   - a payment against a charge belonging to another company or customer
--   - a payment whose category is not the charge's
--   - a new payment, or an increase, against a voided charge
--   - anything that would take the payments against a charge past its amount
--
-- An UPDATE that neither moves the payment to another charge nor raises its
-- amount is let straight through, so checkoff (which flips checked_off) and a
-- downward correction are never blocked, voided charge or not.
--
-- Rows written earlier in the SAME statement are visible to the SUM for a
-- later row (row-level BEFORE triggers see the effects of rows already
-- processed by the outer command), so a multi-row insert is checked row by row
-- against a running total.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.payments_charge_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_charge public.customer_charges%ROWTYPE;
  v_paid   NUMERIC;
BEGIN
  IF NEW.charge_id IS NULL THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE'
     AND NEW.charge_id IS NOT DISTINCT FROM OLD.charge_id
     AND NEW.amount <= OLD.amount THEN
    RETURN NEW;
  END IF;

  SELECT * INTO v_charge
    FROM public.customer_charges
   WHERE id = NEW.charge_id
     FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'charge_guard: charge % does not exist', NEW.charge_id;
  END IF;

  IF v_charge.company_id <> NEW.company_id
     OR v_charge.customer_id IS DISTINCT FROM NEW.customer_id THEN
    RAISE EXCEPTION 'charge_guard: charge % belongs to another customer', NEW.charge_id;
  END IF;

  IF NEW.payment_category_id IS DISTINCT FROM v_charge.payment_category_id THEN
    RAISE EXCEPTION 'charge_guard: payment category does not match charge %', NEW.charge_id;
  END IF;

  IF v_charge.voided_at IS NOT NULL THEN
    RAISE EXCEPTION 'charge_guard: charge % has been voided', NEW.charge_id;
  END IF;

  SELECT COALESCE(SUM(amount), 0) INTO v_paid
    FROM public.payments
   WHERE charge_id = NEW.charge_id
     AND id <> NEW.id;

  IF v_paid + NEW.amount > v_charge.amount THEN
    RAISE EXCEPTION 'charge_guard: charge % owes %, this payment would take it to %',
      NEW.charge_id, v_charge.amount - v_paid, v_paid + NEW.amount;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS payments_charge_guard ON public.payments;
CREATE TRIGGER payments_charge_guard
  BEFORE INSERT OR UPDATE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION public.payments_charge_guard();


-- ---------------------------------------------------------------------------
-- Verify afterwards. Expected results in comments.
-- ---------------------------------------------------------------------------
--   SELECT count(*) FROM customer_charges;
--     -> 0
--
--   SELECT count(*) FROM payments WHERE charge_id IS NOT NULL OR visit_id IS NOT NULL;
--     -> 0   (nothing existing is touched)
--
--   SELECT tgname FROM pg_trigger WHERE tgrelid = 'public.payments'::regclass AND NOT tgisinternal;
--     -> includes payments_charge_guard
